export const data = [
    {
        title: 'California',
        data: [
            {
                x: 'Jan',
                y: 26,
                // tooltip: 'this is a tooltip',
                fill: 'steelblue',
                label: '26',
                labelOnTop: 'Jan',
            },
            {
                x: 'Feb',
                y: 38,
                // tooltip: 'this is a tooltip',
                fill: 'cornflowerblue',
                label: '38',
                labelOnTop: 'Feb',
            },
            {
                x: 'Mar',
                y: 10,
                // tooltip: 'this is a tooltip',
                fill: 'lightblue',
                label: '10',
                labelOnTop: 'Mar',
            },
        ],
    },
    {
        title: 'Ohio',
        data: [
            {
                x: 'Jan',
                y: 12,
                // tooltip: 'this is a tooltip',
                fill: 'steelblue',
                label: '12',
                labelOnTop: 'Jan',
            },
            {
                x: 'Feb',
                y: 38,
                // tooltip: 'this is a tooltip',
                fill: 'cornflowerblue',
                label: '38',
                labelOnTop: 'Feb',
            },
            {
                x: 'Mar',
                y: 42,
                // tooltip: 'this is a tooltip',
                fill: 'lightblue',
                label: '42',
                labelOnTop: 'Mar',
            },
        ],
    },
    {
        title: 'Colorado',
        data: [
            {
                x: 'Jan',
                y: 55,
                // tooltip: 'this is a tooltip',
                fill: 'steelblue',
                label: '55',
                labelOnTop: 'Jan',
            },
            {
                x: 'Feb',
                y: 21,
                // tooltip: 'this is a tooltip',
                fill: 'cornflowerblue',
                label: '21',
                labelOnTop: 'Feb',
            },
            {
                x: 'Mar',
                y: 16,
                // tooltip: 'this is a tooltip',
                fill: 'lightblue',
                label: '16',
                labelOnTop: 'Mar',
            },
        ],
    },
    {
        title: 'Maryland',
        data: [
            {
                x: 'Jan',
                y: 42,
                // tooltip: 'this is a tooltip',
                fill: 'steelblue',
                label: '42',
                labelOnTop: 'Jan',
            },
            {
                x: 'Feb',
                y: 33,
                // tooltip: 'this is a tooltip',
                fill: 'cornflowerblue',
                label: '33',
                labelOnTop: 'Feb',
            },
            {
                x: 'Mar',
                y: 29,
                // tooltip: 'this is a tooltip',
                fill: 'lightblue',
                label: '29',
                labelOnTop: 'Mar',
            },
        ],
    },
    {
        title: 'Virginia',
        data: [
            {
                x: 'Jan',
                y: 38,
                // tooltip: 'this is a tooltip',
                fill: 'steelblue',
                label: '38',
                labelOnTop: 'Jan',
            },
            {
                x: 'Feb',
                y: 26,
                // tooltip: 'this is a tooltip',
                fill: 'cornflowerblue',
                label: '26',
                labelOnTop: 'Feb',
            },
            {
                x: 'Mar',
                y: 17,
                // tooltip: 'this is a tooltip',
                fill: 'lightblue',
                label: '17',
                labelOnTop: 'Mar',
            },
        ],
    },
];
